### ISSUE TITLE
Getting HTTP error 400

### ISSUE THREAD

**Issue by Fudge26** [Capta1nT0ad/TelstraCallToCSV#2]
> python3 -m telstracalltocsv <access_token>

:: Starting export...
   (1/6) 🢃 Downloading 202402... The remote host returned an HTTP error 400.
         HINT: We may be being rate limited.
         HINT: Please run the program again.
         HINT: Otherwise, please file a bug report.

:: Cleaning up...
:: Finished all jobs.

Any logs I can send you or thoughts on this? 
I have tried multiple times using different accounts. 

Configured before hand:
> python3 -m telstracalltocsv --configure

:: Please configure TelstraCallToCSV.
Need help? See the documentation.

 > Account UUID: F0Fxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
 > Phone Number: 03xxxxxxxx

:: Finished all jobs.

**Comment by capta1nt0ad** [comment]
This is unusual, I've never actually seen a 400 doing this before. Could you please run this command, replacing `TOKEN_GOES_HERE`, `ACCOUNT_UUID_GOES_HERE` and `PHONE_NUMBER_GOES_HERE` with the appropriate values?

```sh
curl -X GET -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate, br' -H 'Authorization: Bearer TOKEN_GOES_HERE' -H 'Connection: keep-alive' -H 'correlation-id: 0' -H 'source-system: MyTelstraWeb' 'https://tapi.telstra.com:443/presentation/v1/mytelstra-web/strategic-prepaid/usage-history/itemised?paymentType=prepaid&accountUuid=ACCOUNT_UUID_GOES_HERE&serviceId=PHONE_NUMBER_GOES_HERE&startDate=20240101&endDate=20240201&usageGroup=CALL&pageNumber=1' -w "%{http_code}\n"
```

If it just has a few lines of output, you can probably safely paste it here, however if it returns a whole bunch of jargon that means it was probably successful (and contains personal data), meaning that it would be an issue with TelstraCallToCSV.

**Comment by Fudge26** [comment]
I am just getting errors complaining about the Headers. 



```
Invoke-WebRequest : Cannot bind parameter 'Headers'. Cannot convert the "Accept: */*" value of type "System.String" to type "System.Collections.IDictionary".
At line:1 char:16
+ curl -X GET -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate, br'  ...
+                ~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
    + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.InvokeWebRequestCommand

```

**Comment by capta1nt0ad** [comment]
> I am just getting errors complaining about the Headers. 
> 
> 
> 
> 
> 
> 
> 
> ```
> 
> Invoke-WebRequest : Cannot bind parameter 'Headers'. Cannot convert the "Accept: */*" value of type "System.String" to type "System.Collections.IDictionary".
> 
> At line:1 char:16
> 
> + curl -X GET -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate, br'  ...
> 
> +                ~~~~~~~~~~~~~
> 
>     + CategoryInfo          : InvalidArgument: (:) [Invoke-WebRequest], ParameterBindingException
> 
>     + FullyQualifiedErrorId : CannotConvertArgumentNoMessage,Microsoft.PowerShell.Commands.InvokeWebRequestCommand
> 
> 
> 
> ```

Could you try running curl through Command Prompt instead? I hear that PowerShell aliases it to its own function. 
(EDIT: or you could replace `curl` in the original command with `curl.exe` to force it to run the actual curl executable.)

I haven't fully tested the program on Windows yet (only got to do installation and configuration) and I think my next priority should be fully testing it on Windows.

**Comment by Fudge26** [comment]
My appolgies for not getting back to you sooner on this. Life has been busy.

I had time to run this again and now get the following:

```
            {"status":"FAIL","message":"Error"}
        400
``` 


Using this command with subbed in values. 

```
curl.exe -X GET -H 'Accept: */*' -H 'Accept-Encoding: gzip, deflate, br' -H 'Authorization: Bearer xxxxxxxxxx' -H 'Connection: keep-alive' -H 'correlation-id: 0' -H 'source-system: MyTelstraWeb' 'https://tapi.telstra.com:443/presentation/v1/mytelstra-web/strategic-prepaid/usage-history/itemised?paymentType=prepaid&accountUuid=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxx&serviceId=036382xxxx&startDate=20240101&endDate=20240201&usageGroup=CALL&pageNumber=1' -w "%{http_code}\n"
``` 

I have noticed that when I log in to the telstra portal I get two AccountUUIDs. I can only assume that this is because I am linked to a business account as well as a personal account. This may have something to do with the failure. But just guessing.
I have tried this command with both UUIDs and get the same error out of both.

**Comment by capta1nt0ad** [comment]
I'm sorry, but I don't think that I have any leads on what might be the problem here- I only have one account to test this on. I can only suspect it might be what you described. Sorry about that.

**Comment by Fudge26** [comment]
All good mate. Thanks for trying. Leave it down to having a strange account setup. XD
